default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: apartments_search_development

test:
  <<: *default
  database: apartments_search_test

production:
  <<: *default
  database: apartments_search_production
